FROM scratch
ADD cache/{{CHROOT_DIST}}.tar.bz2 /
ADD conf/apt/sources.list /etc/apt/sources.list
ADD conf/apt/emdebian.list /etc/apt/sources.list.d/emdebian.list

{{APT_CACHE_DOCKER}}

ENV DEBIAN_FRONTEND noninteractive

ENV RPI_TOOLS /opt/rpi-tools
ENV RPI_CHAIN gcc-linaro-arm-linux-gnueabihf-rasbian

RUN apt-key adv --keyserver keyserver.ubuntu.com \
		--recv-keys 7DE089671804772E

RUN git clone https://github.com/raspberrypi/tools.git $RPI_TOOLS --depth 1
ENV PATH $RPI_TOOLS/arm-bcm2708/$RPI_CHAIN/bin:$PATH

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y build-essential \
	kernel-package debhelper qemu-user-static lzop

ENV CROSS_COMPILE arm-linux-gnueabihf-
ENV ARCH arm
